# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import starbound_pb2 as starbound__pb2


class DictSenderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send_dict = channel.unary_unary(
        '/DictSender/send_dict',
        request_serializer=starbound__pb2.Empty.SerializeToString,
        response_deserializer=starbound__pb2.MyDict.FromString,
        )


class DictSenderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send_dict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DictSenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send_dict': grpc.unary_unary_rpc_method_handler(
          servicer.send_dict,
          request_deserializer=starbound__pb2.Empty.FromString,
          response_serializer=starbound__pb2.MyDict.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DictSender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
