# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: starbound.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='starbound.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fstarbound.proto\"h\n\x06MyDict\x12+\n\ndictionary\x18\x01 \x03(\x0b\x32\x17.MyDict.DictionaryEntry\x1a\x31\n\x0f\x44ictionaryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x07\n\x05\x45mpty2,\n\nDictSender\x12\x1e\n\tsend_dict\x12\x06.Empty\x1a\x07.MyDict\"\x00\x62\x06proto3')
)




_MYDICT_DICTIONARYENTRY = _descriptor.Descriptor(
  name='DictionaryEntry',
  full_name='MyDict.DictionaryEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MyDict.DictionaryEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='MyDict.DictionaryEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=123,
)

_MYDICT = _descriptor.Descriptor(
  name='MyDict',
  full_name='MyDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dictionary', full_name='MyDict.dictionary', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MYDICT_DICTIONARYENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=123,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=132,
)

_MYDICT_DICTIONARYENTRY.containing_type = _MYDICT
_MYDICT.fields_by_name['dictionary'].message_type = _MYDICT_DICTIONARYENTRY
DESCRIPTOR.message_types_by_name['MyDict'] = _MYDICT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyDict = _reflection.GeneratedProtocolMessageType('MyDict', (_message.Message,), dict(

  DictionaryEntry = _reflection.GeneratedProtocolMessageType('DictionaryEntry', (_message.Message,), dict(
    DESCRIPTOR = _MYDICT_DICTIONARYENTRY,
    __module__ = 'starbound_pb2'
    # @@protoc_insertion_point(class_scope:MyDict.DictionaryEntry)
    ))
  ,
  DESCRIPTOR = _MYDICT,
  __module__ = 'starbound_pb2'
  # @@protoc_insertion_point(class_scope:MyDict)
  ))
_sym_db.RegisterMessage(MyDict)
_sym_db.RegisterMessage(MyDict.DictionaryEntry)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'starbound_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)


_MYDICT_DICTIONARYENTRY.has_options = True
_MYDICT_DICTIONARYENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_DICTSENDER = _descriptor.ServiceDescriptor(
  name='DictSender',
  full_name='DictSender',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=134,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_dict',
    full_name='DictSender.send_dict',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MYDICT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DICTSENDER)

DESCRIPTOR.services_by_name['DictSender'] = _DICTSENDER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class DictSenderStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.send_dict = channel.unary_unary(
          '/DictSender/send_dict',
          request_serializer=Empty.SerializeToString,
          response_deserializer=MyDict.FromString,
          )


  class DictSenderServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def send_dict(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_DictSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'send_dict': grpc.unary_unary_rpc_method_handler(
            servicer.send_dict,
            request_deserializer=Empty.FromString,
            response_serializer=MyDict.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'DictSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaDictSenderServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def send_dict(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaDictSenderStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def send_dict(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    send_dict.future = None


  def beta_create_DictSender_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('DictSender', 'send_dict'): Empty.FromString,
    }
    response_serializers = {
      ('DictSender', 'send_dict'): MyDict.SerializeToString,
    }
    method_implementations = {
      ('DictSender', 'send_dict'): face_utilities.unary_unary_inline(servicer.send_dict),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_DictSender_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('DictSender', 'send_dict'): Empty.SerializeToString,
    }
    response_deserializers = {
      ('DictSender', 'send_dict'): MyDict.FromString,
    }
    cardinalities = {
      'send_dict': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'DictSender', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
