# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: starbound.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import starbound_pb2


class DictSenderBase(abc.ABC):

    @abc.abstractmethod
    async def send_dict(self, stream):
        pass

    def __mapping__(self):
        return {
            '/DictSender/send_dict': grpclib.const.Handler(
                self.send_dict,
                grpclib.const.Cardinality.UNARY_UNARY,
                starbound_pb2.Empty,
                starbound_pb2.MyDict,
            ),
        }


class DictSenderStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.send_dict = grpclib.client.UnaryUnaryMethod(
            channel,
            '/DictSender/send_dict',
            starbound_pb2.Empty,
            starbound_pb2.MyDict,
        )


class GetConfigBase(abc.ABC):

    @abc.abstractmethod
    async def send_config(self, stream):
        pass

    def __mapping__(self):
        return {
            '/GetConfig/send_config': grpclib.const.Handler(
                self.send_config,
                grpclib.const.Cardinality.UNARY_UNARY,
                starbound_pb2.Empty,
                starbound_pb2.MyConfig,
            ),
        }


class GetConfigStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.send_config = grpclib.client.UnaryUnaryMethod(
            channel,
            '/GetConfig/send_config',
            starbound_pb2.Empty,
            starbound_pb2.MyConfig,
        )
